### ISSUE TITLE
Add a License 

### ISSUE THREAD

**Issue by d3ward** [TheShrewdGamer/SCleaner#1]
I see there is no source code and no License , just a README.md
If you have plans to make the code available, you should think about adding a license

**Comment by ghost** [comment]
Hi @d3ward, Thanks for raising the issue. 

I've no plan to public the source code right now, due to rapid change internal project schema & concepts.  
But I'll update the project Docs Properly very soon with the Release of v1.

Thanks Again :wink:

**Comment by ghost** [comment]
Added "GNU General Public License v3.0"
